spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_dev
    username: app_dev_user
    password: hacking
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true