spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_prod
    username: app_prod_user
    password: hacking
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true